export {
  agentScopeContractInputSchema,
  AgentScopeContractValidationError,
  containsShellControl,
  formatScopeValidationError,
  isHighRiskCommand,
  isRealpathOutsideWorktree,
  isSensitiveScopePath,
  normalizeContractRelativePath,
  normalizeToolPathInsideCwd,
  validateAgentScopeContract,
  type AgentScopeValidationIssue,
  type ValidatedAgentScopeContract,
  type ValidateAgentScopeContractOptions,
} from "./contract"
export {
  buildGuardedRunAudit,
  buildGuardedRunPromptBlock,
  captureGuardedGitStatus,
  classifyGuardedChangedFiles,
  type BuildGuardedRunAuditInput,
  type GuardedGitStatusSnapshot,
} from "./audit"
export {
  classifyClaudeTool,
  classifyObservedToolRisk,
  decideClaudeToolUse,
  extractClaudeToolPaths,
  isPathBlockedByContract,
  isPathInEditableScope,
  isScopePathMatch,
  relativeChangedFilePath,
  toClaudePermissionResult,
  type ClaudeToolCategory,
  type ClassifyObservedToolRiskInput,
  type DecideClaudeToolUseInput,
  type ObservedToolDecision,
  type ObservedToolRisk,
  type ObservedToolRiskCategory,
  type ObservedToolRiskLevel,
} from "./decision"
export {
  getGuardedRunCheckpointAvailability,
  type GuardedRunCheckpointAvailability,
  type GuardedRunCheckpointAvailabilityInput,
} from "./checkpoint"
export {
  applyActiveGuardedScopeExpansion,
  clearActiveGuardedContractsForTest,
  deleteActiveGuardedContract,
  getActiveGuardedContract,
  prepareActiveGuardedRunContract,
  setActiveGuardedContract,
  type ApplyActiveGuardedScopeExpansionResult,
  type PrepareActiveGuardedRunContractResult,
} from "./active-contracts"
